import jieba
URL = 'http://www.cninfo.com.cn/new/hisAnnouncement/query'
HEADERS = {
    'Accept': '*/*',
    'Accept-Encoding': 'gzip, deflate',
    'Accept-Language': 'zh-CN,zh;q=0.9',
    'Connection': 'keep-alive',
    'Content-Length': '181',
    'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
    'Host': 'www.cninfo.com.cn',
    'Origin': 'http://www.cninfo.com.cn',
    'Referer': 'http://www.cninfo.com.cn/new/commonUrl/pageOfSearch?url=disclosure/list/search',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36',
    'X-Requested-With': 'XMLHttpRequest'}
TRADE = ['农、林、牧、渔业', '电力、热力、燃气及水生产和供应业', '交通运输、仓储和邮政业',
         '金融业', '科学研究和技术服务业', '教育', '综合', '采矿业', '建筑业', '住宿和餐饮业',
         '房地产业', '水利、环境和公共设施管理业', '卫生和社会工作', '制造业', '批发和零售业',
         '信息传输、软件和信息技术服务业', '租赁和商务服务业', '居民服务、修理和其他服务业', '文化、体育和娱乐业']

DATA = {
    'pageNum': '',
    'pageSize': 30,
    'column': '',
    'tabName': 'fulltext',
    'plate': '',
    'stock': '',
    'searchkey': '',
    'secid': '',
    'category': '',
    'trade': '',
    'seDate': '',
    'sortName': '',
    'sortType': '',
    'isHLtitle': 'true'
}
STOP_WORDS_DICT = {
    "normal_sw":  ['摘要',
                   '英文',
                   '回复',
                   '细则',
                   '基金',
                   '已取消',
                   '延迟',
                   '提示',
                   '意见',
                   '季度',
                   'eport',
                   '财务指标',
                   '说明',
                   '管理办法',
                   '半年',
                   '半<em>年',
                   '制度',
                   '变更',
                   '表格',
                   '设立',
                   '规则',
                   '签字页',
                   '决议公告',
                   '纲要',
                   '鉴证',
                   '内部控制',
                   '审计',
                   '审核',
                   '债券',
                   '自查',
                   '声明',
                   '整改',
                   '回函',
                   '更正前',
                   '更正公告',
                   '差错更正',
                   '更新前',
                   '修正公告',
                   '修订公告',
                   '更正披露',
                   '更正事项',
                   '专项活动',
                   '方案',
                   '研究报告',
                   '检查',
                   '核查',
                   '补充资料',
                   '补充披露',
                   '补充公告',
                   '补充说明',
                   '补充报告',
                   '的公告',
                   '社会公众',
                   '有限责任',
                   '担保',
                   '责任主体',
                   '季度',
                   '中期',
                   '章程',
                   '意见',
                   '预案',
                   '异常波动',
                   '进展',
                   '资产评估',
                   '督导',
                   '规划',
                   '备忘录',
                   '强制停牌',
                   '无法',
                   '不能',
                   '延期',
                   '规程'],
    "zhaogu_sw": ['提示',
                  '附录',
                  '关于',
                  '虚假',
                  '增发',
                  '摘要',
                  '确认',
                  '澄清',
                  '更正公告',
                  '补充公告',
                  '已取消'],
    "yugao_sw":  ['摘要',
                  '英文',
                  '回复',
                  '细则',
                  '基金',
                  '已取消',
                  '延迟',
                  '意见',
                  'eport',
                  '财务指标',
                  '管理办法',
                  '制度',
                  '表格',
                  '设立',
                  '规则',
                  '签字页',
                  '决议公告',
                  '纲要',
                  '鉴证',
                  '内部控制',
                  '审计',
                  '审核',
                  '债券',
                  '自查',
                  '声明',
                  '整改',
                  '回函',
                  '更正前',
                  '更正公告',
                  '差错更正',
                  '更新前',
                  '修正公告',
                  '修订公告',
                  '更正披露',
                  '更正事项',
                  '专项活动',
                  '方案',
                  '研究报告',
                  '检查',
                  '核查',
                  '补充资料',
                  '补充披露',
                  '补充公告',
                  '补充说明',
                  '补充报告',
                  '社会公众',
                  '有限责任',
                  '担保',
                  '责任主体',
                  '章程',
                  '意见',
                  '预案',
                  '异常波动',
                  '进展',
                  '资产评估',
                  '督导',
                  '规划',
                  '备忘录',
                  '强制停牌',
                  '无法',
                  '不能',
                  '延期',
                  '规程'],
    "wenxun_sw": ['延期', '提示'],
    "quarter_sw": ['摘要',
                   '报表',
                   '业绩',
                   'eport',
                   '更正的公告',
                   '预告',
                   '权益分派',
                   '提示',
                   '持续督导',
                   '减值',
                   '关联交易',
                   '转股',
                   '预案',
                   '意见',
                   '关于更正',
                   '无法',
                   '不能',
                   '不披露',
                   '未披露',
                   '未及时',
                   '延期',
                   '说明',
                   '关于收到'
                   '检查',
                   '的公告',
                   '声明公告',
                   '审议通过',
                   '进展公告',
                   '次会议',
                   '内部控制',
                   '专项报告',
                   '整改',
                   '声明',
                   '风险',
                   '分红派息',
                   '简报',
                   '更正公告',
                   '补充公告',
                   '补充说明',
                   '业务',
                   '英文',
                   '营数据',
                   '取消'],
}

"""
解释：
"search_keys": 检索关键词，当 使用关键词而非巨潮分类 为 1 时启用
"is_duplicate_not_allowed": 1：不允许企业-年度样本有重复，0 反之
"cn_info_column": 巨潮板块
"cn_info_category": 巨潮分类
"stopwords_list": 选择的停用词模块
"""
FILE_INFO_JSON = {
    "A股年报": {
        "search_keys": ["年度报告", "年报"],
        "is_duplicate_not_allowed": 1,
        "cn_info_column": "szse",
        "cn_info_category": "category_ndbg_szsh",
        "stopwords_list": STOP_WORDS_DICT["normal_sw"]
    },
    "A股一季报": {
        "search_keys": ["一季度"],
        "is_duplicate_not_allowed": 1,
        "cn_info_column": "szse",
        "cn_info_category": "category_yjdbg_szsh",
        "stopwords_list": STOP_WORDS_DICT["quarter_sw"]
    },
    "A股半年报": {
        "search_keys": ["半年", "中期"],
        "is_duplicate_not_allowed": 1,
        "cn_info_column": "szse",
        "cn_info_category": "category_bndbg_szsh",
        "stopwords_list": STOP_WORDS_DICT["quarter_sw"]
    },
    "A股三季报": {
        "search_keys": ["三季度"],
        "is_duplicate_not_allowed": 1,
        "cn_info_column": "szse",
        "cn_info_category": "category_sjdbg_szsh",
        "stopwords_list": STOP_WORDS_DICT["quarter_sw"]
    },
    "A股社会责任": {
        "search_keys": ["社会责任", "环境报告书", "ESG", "管治", "治理", "可持续发展"],
        "is_duplicate_not_allowed": 0,
        "cn_info_column": "szse",
        "cn_info_category": "",
        "stopwords_list": STOP_WORDS_DICT["normal_sw"]
    },
    "A股问询函": {
        "search_keys": ["问询", "回复", "回函"],
        "is_duplicate_not_allowed": 0,
        "cn_info_column": "szse",
        "cn_info_category": "",
        "stopwords_list": STOP_WORDS_DICT["wenxun_sw"]
    },
    "A股招股书": {
        "search_keys": ["招股说明书", "招股意向书"],
        "is_duplicate_not_allowed": 0,
        "cn_info_column": "szse",
        "cn_info_category": "",
        "stopwords_list": STOP_WORDS_DICT["zhaogu_sw"]
    },
    "A股业绩报告": {
        "search_keys": ["预告", "快报"],
        "is_duplicate_not_allowed": 0,
        "cn_info_column": "szse",
        "cn_info_category": "category_yjygjxz_szsh",
        "stopwords_list": STOP_WORDS_DICT["yugao_sw"]
    },
    "A股董事会工作报告": {
        "search_keys": ["董事会工作报告"],
        "is_duplicate_not_allowed": 1,
        "cn_info_column": "szse",
        "cn_info_category": "",
        "stopwords_list": STOP_WORDS_DICT["normal_sw"]
    },
    "三板年报": {
        "search_keys": ["年度报告", "年报"],
        "is_duplicate_not_allowed": 1,
        "cn_info_column": "third",
        "cn_info_category": "category_dqgg",
        "stopwords_list": STOP_WORDS_DICT["normal_sw"]
    },
    "三板一季报": {
        "search_keys": ["一季度"],
        "is_duplicate_not_allowed": 1,
        "cn_info_column": "third",
        "cn_info_category": "category_dqgg",
        "stopwords_list": STOP_WORDS_DICT["quarter_sw"]
    },
    "三板半年报": {
        "search_keys": ["半年", "中期"],
        "is_duplicate_not_allowed": 1,
        "cn_info_column": "third",
        "cn_info_category": "category_dqgg",
        "stopwords_list": STOP_WORDS_DICT["quarter_sw"]
    },
    "三板三季报": {
        "search_keys": ["三季度"],
        "is_duplicate_not_allowed": 1,
        "cn_info_column": "third",
        "cn_info_category": "category_dqgg",
        "stopwords_list": STOP_WORDS_DICT["quarter_sw"]
    },
}
